/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vistas;

import com.colegio.Alumno;
import com.colegio.Materia;
import javax.swing.JOptionPane;

/**
 *
 * @author Hernandez Fernando
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioInscripcion
     */
    public FormularioInscripcion() {
        initComponents();
        setSize(800, 600);
        cargarMaterias();
        cargarAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSouth = new javax.swing.JPanel();
        jButtonInscribir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelCenter = new javax.swing.JPanel();
        jLabelLegajo = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jComboBoxMateria = new javax.swing.JComboBox<>();
        jComboBoxAlumno = new javax.swing.JComboBox<>();

        jButtonInscribir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonInscribir.setText("Inscribir");
        jButtonInscribir.setPreferredSize(new java.awt.Dimension(120, 100));
        jButtonInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscribirActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonInscribir);

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setPreferredSize(new java.awt.Dimension(120, 100));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelSouth.add(jButtonSalir);

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.PAGE_END);

        jPanelCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLegajo.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N
        jLabelLegajo.setText("Elija una materia:");
        jPanelCenter.add(jLabelLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelApellido.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N
        jLabelApellido.setText("Elija un alumno");
        jPanelCenter.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jComboBoxMateria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBoxMateria.setPreferredSize(new java.awt.Dimension(141, 65));
        jComboBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMateriaActionPerformed(evt);
            }
        });
        jPanelCenter.add(jComboBoxMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 290, -1));

        jComboBoxAlumno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBoxAlumno.setPreferredSize(new java.awt.Dimension(141, 65));
        jPanelCenter.add(jComboBoxAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 290, -1));

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMateriaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscribirActionPerformed
        // TODO add your handling code here:
        String alumnoSeleccionado = (String) jComboBoxAlumno.getSelectedItem();
        String materiaSeleccionada = (String) jComboBoxMateria.getSelectedItem();
        if (alumnoSeleccionado != null && materiaSeleccionada != null) {
            JOptionPane.showMessageDialog(this, "El alumno: " + alumnoSeleccionado + " a sido inscripto a la carrera: " + materiaSeleccionada);
        }else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un alumno y una materia.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInscribirActionPerformed

    public void cargarAlumnos() {
        for (Alumno alumno: VistaPrincipal.alumnosSet) {
            jComboBoxAlumno.addItem(alumno.getNombre() +" "+ alumno.getApellido());
        }
    }
    
    public void cargarMaterias() {
        for (Materia materia: VistaPrincipal.materiasSet) {
            jComboBoxMateria.addItem(materia.getNombre() +" "+ materia.getIdMateria());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInscribir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxAlumno;
    private javax.swing.JComboBox<String> jComboBoxMateria;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelLegajo;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSouth;
    // End of variables declaration//GEN-END:variables
}
